{% set name = "CompStats" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CompStats-{{ version }}.tar.gz
  sha256: 497c20df415b586da17c2f9a774acb9765f5e041587e33217be707b3fcbc2c1f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - scikit-learn >=1.3.0
    - pandas
    - seaborn
    - python >=3.7

test:
  imports:
    - CompStats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/CompStats
  summary: Competition Statistics
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
