{% set name = "CompStats" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CompStats-{{ version }}.tar.gz
  sha256: 6634d86b101b4a8d6cdf3737187630b2471c70563331913173be976a629e23a1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  
requirements:
  host:
    - pip
    - python >=3.7
  run:
    - scikit-learn >=1.3.0
    - pandas
    - seaborn
    - python >=3.7

test:
  imports:
    - CompStats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/CompStats
  summary: Competition Statistics
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
